# =====================================================
# AutoFireWorkRegions
# Плагин разработан командой проекта FlexCraft - Хэлфи ツ
# Discord: https://discord.gg/KSdY9z4Fb9
# =====================================================

interval-seconds: 1

zones:
  spawn:
    world: spawn
    min:
      x: -171
      y: -30
      z: -293
    max:
      x: 355
      y: 318
      z: 473

firework:
  power: 3

  # СКОЛЬКО ФЕЙЕРВЕРКОВ ЗА ОДИН ЗАПУСК
  burst-min: 5
  burst-max: 15

  # СКОЛЬКО ТОЧЕК ЗА ИНТЕРВАЛ
  locations-per-interval: 3

  colors:
    - RED
    - BLUE
    - AQUA
    - PURPLE
    - LIME
    - ORANGE
    - YELLOW

