# =====================================================
# AutoFireWorkRegions
# Плагин разработан командой проекта FlexCraft - Хэлфи ツ
# Discord: https://discord.gg/KSdY9z4Fb9
# =====================================================

interval-seconds: 10

zones:
  spawn:
    world: world
    min:
      x: -692
      y: 65
      z: -1187
    max:
      x: -522
      y: 90
      z: -1057

firework:
  power: 2
  colors:
    - RED
    - BLUE
    - AQUA
    - PURPLE
    - LIME
    - ORANGE
    - YELLOW
